# Generated by Django 5.0 on 2026-02-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("athlete", "运动员"),
                    ("organizer", "组织者"),
                    ("referee", "裁判"),
                    ("admin", "管理员"),
                ],
                default="athlete",
                help_text="用户角色类型",
                max_length=20,
                verbose_name="用户类型",
            ),
        ),
    ]
