# Generated by Django 5.0 on 2026-02-02 00:00

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                _("username"),
                max_length=150,
                unique=True,
                help_text=_('Required. 150 characters or fewer.'),
                validators=[],
                error_messages={
                    'unique': _("A user with that username already exists."),
                },
            ),
        ),
    ]
