# Generated by Django 5.0 on 2026-01-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="系统自动生成",
                        max_length=50,
                        unique=True,
                        verbose_name="报名编号",
                    ),
                ),
                (
                    "participant_name",
                    models.CharField(max_length=50, verbose_name="参赛者姓名"),
                ),
                (
                    "participant_phone",
                    models.CharField(max_length=11, verbose_name="参赛者电话"),
                ),
                (
                    "participant_id_card",
                    models.CharField(max_length=18, verbose_name="参赛者身份证"),
                ),
                (
                    "participant_gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        max_length=1,
                        verbose_name="参赛者性别",
                    ),
                ),
                (
                    "participant_birth_date",
                    models.DateField(verbose_name="参赛者出生日期"),
                ),
                (
                    "participant_organization",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="参赛者单位"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(max_length=50, verbose_name="紧急联系人"),
                ),
                (
                    "emergency_phone",
                    models.CharField(max_length=11, verbose_name="紧急联系电话"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未支付"),
                            ("paid", "已支付"),
                            ("refunded", "已退款"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
                (
                    "review_remarks",
                    models.TextField(blank=True, null=True, verbose_name="审核备注"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="赛事",
                    ),
                ),
            ],
            options={
                "verbose_name": "报名",
                "verbose_name_plural": "报名",
                "db_table": "registration",
                "ordering": ["-created_at"],
            },
        ),
    ]
