# Generated by Django 5.0 on 2026-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="赛事名称")),
                (
                    "description",
                    models.TextField(
                        help_text="详细的赛事介绍", verbose_name="赛事描述"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/%Y/%m/",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="如：田径、游泳、篮球等",
                        max_length=50,
                        verbose_name="赛事类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("international", "国际级"),
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("city", "市级"),
                            ("school", "校级"),
                        ],
                        default="school",
                        max_length=20,
                        verbose_name="赛事级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("ongoing", "进行中"),
                            ("finished", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="赛事状态",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="比赛地点")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "registration_start",
                    models.DateTimeField(verbose_name="报名开始时间"),
                ),
                ("registration_end", models.DateTimeField(verbose_name="报名截止时间")),
                (
                    "max_participants",
                    models.IntegerField(
                        default=0, help_text="0表示不限制", verbose_name="最大参赛人数"
                    ),
                ),
                (
                    "current_participants",
                    models.IntegerField(default=0, verbose_name="当前报名人数"),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="单位：元",
                        max_digits=10,
                        verbose_name="报名费用",
                    ),
                ),
                (
                    "rules",
                    models.TextField(blank=True, null=True, verbose_name="比赛规则"),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, null=True, verbose_name="参赛要求"),
                ),
                (
                    "prizes",
                    models.TextField(blank=True, null=True, verbose_name="奖项设置"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=11, verbose_name="联系电话"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="联系邮箱"
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="推荐到首页展示",
                        verbose_name="是否推荐",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "赛事",
                "verbose_name_plural": "赛事",
                "db_table": "event",
                "ordering": ["-created_at"],
            },
        ),
    ]
