# Generated by Django 5.0 on 2026-01-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="组织者",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "-created_at"], name="event_status_77ade7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["event_type"], name="event_event_t_4c9c3b_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_time"], name="event_start_t_a7590c_idx"),
        ),
    ]
