# Generated by Django 5.0 on 2026-01-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.CharField(
                blank=True,
                help_text="图片路径，如：/images/events/xxx.jpg",
                max_length=500,
                null=True,
                verbose_name="封面图片",
            ),
        ),
    ]
