# Generated by Django 5.0 on 2026-02-01 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_cover_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("preliminary", "初赛"),
                            ("semifinal", "半决赛"),
                            ("final", "决赛"),
                        ],
                        max_length=20,
                        verbose_name="轮次",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分配人",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="events.event",
                        verbose_name="赛事",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "referee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="裁判",
                    ),
                ),
            ],
            options={
                "verbose_name": "赛事任务",
                "verbose_name_plural": "赛事任务",
                "db_table": "event_assignment",
                "ordering": ["-assigned_at"],
            },
        ),
    ]
