# Generated by Django 5.0 on 2026-02-01 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefereeEventAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_accesses",
                        to="events.event",
                        verbose_name="赛事",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "referee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="裁判",
                    ),
                ),
            ],
            options={
                "db_table": "referee_event_access",
                "verbose_name": "裁判赛事访问",
                "verbose_name_plural": "裁判赛事访问",
                "ordering": ["-created_at"],
                "unique_together": {("referee", "event"),},
            },
        ),
    ]
