# Generated by Django 5.0 on 2026-01-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "问题反馈"),
                            ("suggestion", "功能建议"),
                            ("complaint", "投诉"),
                            ("praise", "表扬"),
                            ("other", "其他"),
                        ],
                        default="suggestion",
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        help_text="存储多张图片的URL列表",
                        null=True,
                        verbose_name="图片列表",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        help_text="用户的联系方式",
                        max_length=100,
                        null=True,
                        verbose_name="联系方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "reply",
                    models.TextField(blank=True, null=True, verbose_name="回复内容"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="匿名反馈不显示用户信息",
                        verbose_name="是否匿名",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="如果是关于某个赛事的反馈",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="events.event",
                        verbose_name="关联赛事",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈",
                "verbose_name_plural": "反馈",
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
