# Generated by Django 5.0 on 2026-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="carousel/%Y/%m/", verbose_name="轮播图片"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="点击轮播图跳转的URL",
                        null=True,
                        verbose_name="链接地址",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("home", "首页"),
                            ("event", "赛事页"),
                            ("announcement", "公告页"),
                        ],
                        default="home",
                        max_length=20,
                        verbose_name="展示位置",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="定时展示的开始时间",
                        null=True,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="定时展示的结束时间",
                        null=True,
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "click_count",
                    models.IntegerField(default=0, verbose_name="点击次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "轮播图",
                "db_table": "carousel",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
