# Generated by Django 5.0 on 2026-01-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carousel", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carousel",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carousels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="carousel",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carousels",
                to="events.event",
                verbose_name="关联赛事",
            ),
        ),
        migrations.AddIndex(
            model_name="carousel",
            index=models.Index(
                fields=["position", "is_active", "order"],
                name="carousel_positio_f35c9f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carousel",
            index=models.Index(
                fields=["is_active"], name="carousel_is_acti_5ff289_idx"
            ),
        ),
    ]
