# Generated by Django 5.0 on 2026-01-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carousel", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carousel",
            name="image",
            field=models.CharField(
                help_text="图片路径，如：/images/carousel/xxx.jpg",
                max_length=500,
                verbose_name="轮播图片",
            ),
        ),
    ]
