# Generated by Django 5.0 on 2026-01-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("announcements", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布者",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="赛事公告需要关联赛事",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="events.event",
                verbose_name="关联赛事",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["announcement_type"], name="announcemen_announc_1e1407_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["is_published", "-publish_time"],
                name="announcemen_is_publ_051df3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["-is_pinned"], name="announcemen_is_pinn_d6ba68_idx"
            ),
        ),
    ]
